#!/usr/bin/env bash
# Using SCP to move files

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi