#!/usr/bin/env bash
# installing nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
searchstring="^\tlocation / {"
replacestring="\tlocation /redirect_ {\n\treturn 301 \$scheme:https://www/youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@${searchstring}@${replacestring}@" /etc/nginx/sites-available/default
sudo service nginx restart
