#!/usr/bin/env bash
#  custom 404 page that contains the string
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sudo touch /var/www/html/error404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html

searchstring="^\tlocation / {"
replacestring="error_page 404 /error404.html;\n\n\tlocation /redirect_me {\n\treturn 301 \$scheme:https://www/youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@${searchstring}@${replacestring}@" /etc/nginx/sites-available/default
sudo service nginx restart
