#!/usr/bin/env bash
#  custom 404 page that contains the string
sudo apt-get -y update
sudo apt-get -y upgrade
sudo spt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sudo touch /var/www/html/error404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html

searchscting = "^\tlocation / {"
replacestring = "\tlocation /redirect_ {\n\t\return 301 \$scheme:https://www/youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@${searchstring}@${replacestring}@" /etc/ngnx/sites-available/default
sudo service nginx restart
