#!/usr/bin/env bash
#  installing haproxy

sudo apt-get -y upgrade
sudo apt-get -y update

sudo apt-get -y install haproxy

str="\nfrontend http_web\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend custom_backend\n\nbackend custom_backend\n\tbalance roundrobin\n\tserver web01 3.84.180.190:80 check\n\tserver web02 54.82.73.173:80 check"

sudo echo -e $str | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
