#!/usr/bin/env bash
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signa
trap 'echo I am invincible!!!' SIGTERM
while true
do
    echo "to infinity and Beyond"
    sleep 2
done
