#!/usr/bin/env bash
# script that displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line

i=0

while [ $i -le 9 ]
do
    if [ $i -eq 8 ]
    then
        echo "Holberton School"
        echo "Hi"
    else
        echo "Holberton School"
    fi
    ((i++))
done