#!/usr/bin/env bash
# script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
# use cut delimiter "-" and display the second field

for file in *; do
    echo "$file" | cut -d "-" -f 2
done
